apiVersion: v1
kind: Service
metadata:
  name: honeypot-service
  namespace: wasmpot-namespace
spec:
  selector:
    app: wasmpot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Assure-toi que cela correspond au port du conteneur
  type: NodePort
